language: go
sudo: false
go:
  - 1.7
  - 1.8
install:
  - go generate
  - go get -u github.com/mitchellh/gox && env BUILD_ALL=1 go generate
script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
notifications:
  email:
    on_success: never
    on_failure: always
