language: go
sudo: false
go:
  - 1.8
  - 1.8.3
  - 1.9
  - tip
go_import_path: ekyu.moe/sha3sum
install:
  - go get -t ./...
  - go generate
  - go get -u github.com/mitchellh/gox && gox -ldflags "-s -w" -output release/{{.OS}}_{{.Arch}}/... ekyu.moe/sha3sum/...
script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
notifications:
  email:
    on_success: never
    on_failure: always
